---
- name: ping test
  hosts: apiserver
  gather_facts: false
  tasks:
    - name: ping
      shell: echo 1 > /root/tmp.txt
  

  # ---
# - hosts: apiserver
#   serial: 1
#   roles:
#    - deploy-apiserver
