---
- name: set register if jinho9610/node-express-app:latest exists
  shell: echo $(docker images | grep jinho9610/node-express-app | wc -l)
  register: imageExists

- name: remove images
  shell: docker rmi $(docker images --format {{ '{{.Repository}}:{{.Tag}}' }} | grep jinho9610/node-express-app)

- name: run console api server on docker container
  shell: docker run --name node-express -d -p 5555:5555 jinho9610/node-express-app:latest
  # docker_container:
  #   name: node-express
  #   image: jinho9610/node-express-app:latest
  #   state: started
  #   recreate: true
  #   restart_policy: always
  #   user: root
  #   ports: 5555:5555